name = "digu-league"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "digu-league-db"
database_id = "2aa9c8d5-df52-4016-8ac4-e8e5258e93b2"
migrations_dir = "migrations"
