ALTER TABLE games ADD COLUMN t1_p1_cards INTEGER;
ALTER TABLE games ADD COLUMN t1_p2_cards INTEGER;
ALTER TABLE games ADD COLUMN t2_p1_cards INTEGER;
ALTER TABLE games ADD COLUMN t2_p2_cards INTEGER;
ALTER TABLE games ADD COLUMN gin_player_id TEXT;
